# Copyright IBM Corp. 2018, 2023
# SPDX-License-Identifier: MPL-2.0

global:
  datacenter: dc1

ui:
  service:
    type: "LoadBalancer"

connectInject:
  enabled: true

controller:
  enabled: true

server:
  replicas: 1
